services:
  # Backend API service
  - type: web
    name: correcte-ai-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

  # Frontend service
  - type: web
    name: correcte-ai-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        fromService:
          name: correcte-ai-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL
        append: /api
